Happy path working
No handling of test failures yet.
In fact the Circle check is commented out.

diff --git a/.github/workflows/merge-queue.yml b/.github/workflows/merge-queue.yml
--- a/.github/workflows/merge-queue.yml
+++ b/.github/workflows/merge-queue.yml
@@ -42,8 +42,8 @@ jobs:
               ref: pullRequest.data.head.ref
             });
 
-            core.info(`checks: ${JSON.stringify(checks.data)}`);
-            core.info(`pullRequest: ${JSON.stringify(pullRequest.data)}`);
+            # core.info(`checks: ${JSON.stringify(checks.data)}`);
+            # core.info(`pullRequest: ${JSON.stringify(pullRequest.data)}`);
 
             if (!pullRequest.data.rebaseable) {
               await github.rest.issues.createComment({
@@ -70,6 +70,17 @@ jobs:
     permissions: write-all
 
     steps:
+      - name: Get PR source branch
+        id: get_pr_branch
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          set -euo pipefail
+
+          pr_url="${{ github.event.issue.pull_request.url }}"
+          branch=$(gh api "$pr_url" --jq .head.ref)
+          echo "branch=$branch" >> "$GITHUB_OUTPUT"
+
       - name: Ensure merge state branch exists
         id: ensure_merge_state_branch
         uses: actions/github-script@v7
@@ -99,24 +110,171 @@ jobs:
           # get the latest current merge branch counter
           set -euo pipefail
 
-          # git fetch origin merge-queue-state
-          git checkout origin/merge-queue-state -b merge-queue-state-working
+          echo "1"
 
-          currentBranchCounter=$(jq '.branchCounter' state.json)
-          next=$((currentBranchCounter + 1))
+          git fetch origin merge-queue-state
+          echo "2"
+          git checkout merge-queue-state
 
-          echo "yes"
-          echo "branchCounter=$(next)"
-          echo "no"
-          echo "branchCounter=$(next)" >> "$GITHUB_OUTPUT"
+          echo "3"
 
-      # - name: Write new branch counter
-      #   id: write_branch_counter
+          branch_counter=$(jq '.branchCounter' state.json)
+          echo "4"
+          # nextBranchCounter=$((branchCounter + 1))
+          echo "branch_counter=$branch_counter"
+          echo "branch_counter=$branch_counter" >> "$GITHUB_OUTPUT"
+          echo "merge_branch=merge-branch-$((branch_counter + 1))"
+          echo "merge_branch=merge-branch-$((branch_counter + 1))" >> "$GITHUB_OUTPUT"
+          echo "5"
+
+      - name: Create merge branch
+        id: create_merge_branch
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # branch off the latest merge queue branch and add to it
+          set -euo pipefail
+
+          git config --global user.email "queue_bot@jakeprime.com"
+          git config --global user.name "Q-bot"
+
+
+          branch_counter=${{steps.get_queue_counter.outputs.branch_counter}}
+          branch_name=${{ steps.get_queue_counter.outputs.branch_name }}
+
+          if git show-ref --verify --quiet refs/heads/merge-branch-$branch_counter; then
+            base_branch=merge-branch-$branch_counter
+          else
+            base_branch=main
+          fi
+
+          branch_counter=$((branch_counter + 1))
+
+          echo 1
+          git fetch origin $base_branch && git checkout $base_branch
+          echo 2
+          git fetch origin ${{steps.get_pr_branch.outputs.branch}} && git checkout ${{steps.get_pr_branch.outputs.branch}}
+          echo 3
+          git rebase --rebase-merges $base_branch
+          echo 4
+          git push --force --set-upstream origin HEAD:${{steps.get_pr_branch.outputs.branch}}
+
+          echo 4
+          git switch $base_branch
+          echo 5
+          git checkout -b merge-branch-$branch_counter
+          echo "Created branch merge-branch-$branch_counter"
+          echo 6
+          git merge ${{steps.get_pr_branch.outputs.branch}} --no-ff
+          echo 7
+          git push --set-upstream origin HEAD:merge-branch-$branch_counter
+          echo 8
+          # git push --set-upstream origin HEAD
+          # TODO: handle failure to rebase
+
+          echo "something something"
+          echo "$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs --jq '.check_runs[].name')"
+          echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
+          echo "branch_counter=$branch_counter" >> "$GITHUB_OUTPUT"
+
+      - name: Write new branch counter
+        id: write_branch_counter
+        run: |
+          set -euo pipefail
+
+          branch_counter=${{steps.create_merge_branch.outputs.branch_counter}}
+          echo "$branch_counter"
+
+          git fetch origin merge-queue-state
+          git checkout merge-queue-state
+          jq ".branchCounter = $branch_counter" state.json > tmp && mv tmp state.json
+
+          git config --global user.email "queue_bot@jakeprime.com"
+          git config --global user.name "Q-bot"
+
+          git add state.json
+          git commit -m "Incrementing merge queue counter"
+          git push origin HEAD:merge-queue-state
+
+      # - name: Wait for CircleCI to pass
+      #   id: wait_for_ci
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
       #   run: |
-      #     set -euo pipefail
+      #     REPO=${{ github.repository }}
+      #     SHA=${{ steps.create_merge_branch.outputs.sha }}
 
-      #     jq ".currentBranchCounter = ${{steps.get_queue_counter.outputs.branchCounter}}" state.json > state.json
+      #     for i in {1..60}; do
+      #       result=$(gh api repos/$REPO/commits/$SHA/status)
 
-      #     git add state.json
-      #     git commit -m "Incrementing merge queue counter"
-      #     git push origin HEAD:merge-queue-state
+      #       state=$(echo "$result" | jq -r '.state')
+
+      #       echo "Status state: $state"
+
+      #       if [ "$state" = "success" ]; then
+      #         echo "✅ All statuses passed"
+      #         exit 0
+      #       elif [ "$state" = "failure" ]; then
+      #         echo "❌ One or more statuses failed"
+      #         exit 1
+      #       fi
+
+      #       echo "Waiting for statuses..."
+      #       sleep 10
+      #     done
+
+      #     echo "⏰ Timed out waiting for commit status"
+      #     exit 1
+
+      # - name: Checkout merge-branch-x branch
+      #   uses: actions/checkout@v4
+      #   with:
+      #     fetch-depth: 0
+      #     # ref: ${{ steps.get_queue_counter.outputs.merge_branch }}
+
+      - name: Merge into main
+        id: merge_to_main
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          REPO=${{ github.repository }}
+          SHA=${{ steps.create_merge_branch.outputs.sha }}
+          PR_URL=${{ github.event.issue.pull_request.url }}
+          PR_NUMBER=$(basename "$PR_URL")
+
+          git fetch origin main && git checkout main
+          git fetch origin ${{ steps.get_queue_counter.outputs.merge_branch }} && git checkout ${{ steps.get_queue_counter.outputs.merge_branch }}
+          git switch main
+          git merge ${{ steps.get_queue_counter.outputs.merge_branch }}
+          git push -u origin HEAD:main
+
+          # echo "gh api -X PUT repos/$REPO/pulls/$PR_NUMBER/merge -f merge_method=merge"
+
+          # gh api \
+          #   -X PUT \
+          #   repos/$REPO/pulls/$PR_NUMBER/merge \
+          #   -f merge_method=rebase
+
+          # echo "git fetch"
+          # git fetch
+
+          # echo "git fetch origin ${{ steps.get_queue_counter.outputs.merge_branch }}"
+          # git fetch origin ${{ steps.get_queue_counter.outputs.merge_branch }}
+
+          # echo "git fetch origin ${{steps.get_pr_branch.outputs.branch}} && git checkout ${{steps.get_pr_branch.outputs.branch}}"
+          # git fetch origin ${{steps.get_pr_branch.outputs.branch}} && git checkout ${{steps.get_pr_branch.outputs.branch}}
+
+          # echo "git reset --hard origin/${{steps.get_pr_branch.outputs.branch}}"
+          # git reset --hard origin/${{steps.get_pr_branch.outputs.branch}}
+
+          # echo "git push --force-with-lease"
+          # git push --force-with-lease
+
+          # echo "git fetch origin main && git checkout main"
+          # git fetch origin main && git checkout main
+
+          # echo "git merge ${{steps.get_pr_branch.outputs.branch}}"
+          # git merge ${{steps.get_pr_branch.outputs.branch}} --no-ff
+
+          # echo "git push"
+          # git push
