wip

diff --git a/.github/workflows/merge-queue.yml b/.github/workflows/merge-queue.yml
--- a/.github/workflows/merge-queue.yml
+++ b/.github/workflows/merge-queue.yml
@@ -70,6 +70,17 @@ jobs:
     permissions: write-all
 
     steps:
+      - name: Get PR source branch
+        id: get_pr_branch
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          set -euo pipefail
+
+          pr_url="${{ github.event.issue.pull_request.url }}"
+          branch=$(gh api "$pr_url" --jq .head.ref)
+          echo "branch=$branch" >> "$GITHUB_OUTPUT"
+
       - name: Ensure merge state branch exists
         id: ensure_merge_state_branch
         uses: actions/github-script@v7
@@ -99,24 +110,65 @@ jobs:
           # get the latest current merge branch counter
           set -euo pipefail
 
-          # git fetch origin merge-queue-state
-          git checkout origin/merge-queue-state -b merge-queue-state-working
+          git fetch origin merge-queue-state
+          git checkout merge-queue-state
 
-          currentBranchCounter=$(jq '.branchCounter' state.json)
-          next=$((currentBranchCounter + 1))
+          currentBranchCounter=$(jq '.currentBranchCounter' state.json)
+          # nextBranchCounter=$((currentBranchCounter + 1))
+          echo "branchCounter=$currentBranchCounter"
+          echo "branchCounter=$currentBranchCounter" >> "$GITHUB_OUTPUT"
 
-          echo "yes"
-          echo "branchCounter=$(next)"
-          echo "no"
-          echo "branchCounter=$(next)" >> "$GITHUB_OUTPUT"
+      - name: Create merge branch
+        id: create_merge_branch
+        run: |
+          # branch off the latest merge queue branch and add to it
+          set -euo pipefail
 
-      # - name: Write new branch counter
-      #   id: write_branch_counter
-      #   run: |
-      #     set -euo pipefail
+          git config --global user.email "queue_bot@jakeprime.com"
+          git config --global user.name "Q-bot"
 
-      #     jq ".currentBranchCounter = ${{steps.get_queue_counter.outputs.branchCounter}}" state.json > state.json
+          echo "1"
 
-      #     git add state.json
-      #     git commit -m "Incrementing merge queue counter"
-      #     git push origin HEAD:merge-queue-state
+          branch_counter=${{steps.get_queue_counter.outputs.branchCounter}}
+          echo "2"
+
+          if git show-ref --verify --quiet refs/heads/merge-queue-$branch_counter; then
+            base_branch=merge-queue-$branch_counter
+          else
+            base_branch=main
+          fi
+          echo "3"
+
+          branch_counter=$((branch_counter + 1))
+
+          echo "4"
+          # start with the branch for this PR
+          echo "git checkout ${{steps.get_pr_branch.outputs.branch}}"
+          git fetch origin ${{steps.get_pr_branch.outputs.branch}} && git checkout ${{steps.get_pr_branch.outputs.branch}}
+          echo "5"
+          # create a merge branch from it
+          git checkout -b merge-branch-$branch_counter
+          echo "6"
+          # rebase it on top of whatever the latest merge candidate is
+          git fetch origin $base_branch && git rebase origin/$base_branch
+
+          echo "7"
+          git push --set-upstream origin HEAD
+          # TODO: handle failure to rebase
+
+      - name: Write new branch counter
+        id: write_branch_counter
+        run: |
+          set -euo pipefail
+
+          branchCounter=${{steps.get_queue_counter.outputs.branchCounter}}
+          echo "$branchCounter"
+
+          jq ".currentBranchCounter = $branchCounter" state.json > tmp && mv tmp state.json
+
+          git config --global user.email "queue_bot@jakeprime.com"
+          git config --global user.name "Q-bot"
+
+          git add state.json
+          git commit -m "Incrementing merge queue counter"
+          git push origin HEAD:merge-queue-state
