Wait for branch to be front of queue

diff --git a/.github/workflows/q-bot.yml b/.github/workflows/q-bot.yml
--- a/.github/workflows/q-bot.yml
+++ b/.github/workflows/q-bot.yml
@@ -75,17 +75,27 @@ jobs:
           merge_branch=${{ steps.load_state.outputs.merge_branch }}
           pr_branch=${{ steps.load_state.outputs.pr_branch }}
 
-          git fetch origin $base_branch $pr_branch
+          git fetch origin $base_branch $pr_branch --unshallow
 
-          git checkout $pr_branch
-          git rebase --rebase-merges origin/$base_branch
-
-          git checkout $base_branch
+          git checkout $base_branch && git pull
           git checkout -b $merge_branch
-          git merge --no-ff $pr_branch
+
+          git log --oneline --decorate --graph
+
+          git checkout $pr_branch && git pull
+          git rebase $merge_branch
+
+
+          git log --oneline --decorate --graph
+
+          # git checkout $base_branch
+          # git checkout -b $merge_branch
+
+          git merge --no-edit --no-ff $pr_branch
           git push --set-upstream origin HEAD:$merge_branch
 
           sha=$(git rev-parse --short HEAD)
+          echo "sha=$sha" >> "$GITHUB_OUTPUT"
 
           git log --oneline --decorate --graph
 
@@ -119,7 +129,61 @@ jobs:
       - name: Unlock merge queue state
         run: .github/scripts/unlock-merge-queue-state.sh
 
-        # - name: Wait for successful CI
+      - name: Wait for CircleCI to pass
+        id: wait_for_ci
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          REPO=${{ github.repository }}
+          SHA=${{ steps.create_merge_branch.outputs.sha }}
+
+          for i in {1..60}; do
+
+            result=$(gh api repos/$REPO/commits/$SHA/status)
+
+            state=$(echo "$result" | jq -r '.state')
+
+            echo "Status state: $state"
+
+            if [ "$state" = "success" ]; then
+              echo "✅ All statuses passed"
+              exit 0
+            elif [ "$state" = "failure" ]; then
+              echo "❌ One or more statuses failed"
+              exit 1
+            fi
+
+            echo "Waiting for statuses..."
+            sleep 10
+          done
+
+          echo "⏰ Timed out waiting for commit status"
+          exit 1
+
+      - name: Wait until first in queue
+        run: |
+          merge_branch=${{ steps.load_state.outputs.merge_branch }}
+
+          for i in {1..12}; do
+            git fetch origin merge-queue-state --depth 1
+
+            first_branch=$(
+              git show origin/merge-queue-state:state.json |
+              jq -r '.mergeBranches | min_by(.count) | .name'
+            )
+
+            echo "comparing $merge_branch with $first_branch"
+
+            if [[ "$merge_branch" == "$first_branch" ]]; then
+              exit 0
+            fi
+
+            echo "Waiting for queue position"
+            sleep 5
+          done
+
+          echo "⏰ Timed out waiting for queue position"
+          exit 1
 
       - name: Lock merge queue state
         run: .github/scripts/lock-merge-queue-state.sh
@@ -132,26 +196,30 @@ jobs:
           merge_branch=${{ steps.load_state.outputs.merge_branch }}
           pr_branch=${{ steps.load_state.outputs.pr_branch }}
 
-          # git checkout $pr_branch
-          # git rebase --rebase-merges $base_branch
-          # git push --force-with-lease
-          # git checkout main
-          # git pull
-          # git reset --hard $merge_branch
-          # git push --force-with-lease
+          git fetch origin main $pr_branch
+          git checkout $pr_branch && git reset --hard origin/$pr_branch
+          git rebase origin/main
+          echo "pushing pr branch"
+          git push --force-with-lease origin HEAD:$pr_branch
 
-          # git push --delete origin $merge_branch
-          # git push --delete origin $pr_branch
 
-          # git checkout merge-queue-state
-          # git pull
-          # cat state.json
-          # jq \
-          #   --arg name "$merge_branch" \
-          #   '.mergeBranches |= map(select(.name != $name))' state.json > tmp && mv tmp state.json
-          # git add state.json
-          # git commit -m '$merge_branch has been successfully merged'
-          # git push
+          git checkout main && git pull
+          echo "merging main"
+          git merge $pr_branch --no-ff
+          echo "pushing main"
+          git push
+
+          git push --delete origin $merge_branch
+
+          git checkout merge-queue-state
+          git pull
+          cat state.json
+          jq \
+            --arg name "$merge_branch" \
+            '.mergeBranches |= map(select(.name != $name))' state.json > tmp && mv tmp state.json
+          git add state.json
+          git commit -m '$merge_branch has been successfully merged'
+          git push
 
           cat state.json
 
